# Generated by Django 4.2 on 2023-07-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_user',
            name='subjects',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
