# Generated by Django 4.2 on 2023-07-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_student_user_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjectname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=100)),
                ('sub_id', models.IntegerField(default=None)),
            ],
        ),
    ]
