# Generated by Django 4.2 on 2023-07-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_subjectname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectname',
            name='sub_id',
        ),
    ]
