# Generated by Django 4.2 on 2023-07-12 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_remove_subjectname_sub_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subjectname',
        ),
        migrations.AddField(
            model_name='student_user',
            name='classe',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
